import React, { Suspense } from "react";
// import { Link } from "react-router-dom";
import { Helmet } from "react-helmet";
import Footer from "../components/Footer";
import AboutSection from "./AboutSection";
import HomeSection from "./HomeSection";
// import HomeSection1 from "/HomeSection1";
import { Box, Image, Flex } from "@chakra-ui/react";

import HomeButton from "components/HomeButton";

// todo: create referenced (linked) pages
// const Home = () => {
//     return (
//         <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
//             <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
//             <p style={{ fontSize: "18px", marginBottom: "30рх" }}>
//                 This project was generated By{" "}
//                 <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                     Dhiwise
//                 </a>
//                 . Quickly use below links to navigate through all pages.
//             </p>

//             <ul style={{ liststyle: "none", padding: "g" }}>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/myclassrooms" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         MyClassrooms </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/instructions"
//                         style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         Instructions
//                     </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/login" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         Login </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/mycustompiecesnutriscore" style={{
//                         color: "#87CEFA"
//                         , textDecoration: "none"
//                     }}>
//                         • MyCustomPiecesNutriScore
//                     </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/mycustompieces" style={{
//                         color:
//                             "#87CEFA", textDecoration: "none"
//                     }}>
//                         MyCustomPieces
//                     </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/browsecustompieces" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         BrowseCustomPieces </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/mycustompiecesaddnewpiece" style={{
//                         color:
//                             "#87CEFA", textDecoration: "none"
//                     }}>
//                         MyCustomPiecesAddNewPiece
//                     </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/mycustompiecesdeletecategory" style={{
//                         color:
//                             "#87CEFA", textDecoration: "none"
//                     }}>
//                         MyCustomPiecesDeleteCategory </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/browsedpiece" style={{
//                         color: "#87CEFA", textDecoration: "none"
//                     }}>
//                         BrowsedPiece </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/newpiece" style={{
//                         color:
//                             "#87CEFA", textDecoration: "none"
//                     }}>
//                         NewPiece </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/modifiednewpiece" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         ModifiedNewPiece </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/examplesproductdetailpage" style={{
//                         color:
//                             "#87CEFA", textDecoration: "none"
//                     }}>
//                         ExamplesProductDetailPage </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/browsedpieceaddtoclass" style={{
//                         color:
//                             "#87CEFA"
//                         , textDecoration: "none"
//                     }}>
//                         BrowsedPieceAddtoClass
//                     </Link>
//                 </li>
//                 <li style={{ marginBottom: "10px" }}>
//                     <Link to="/newpieceimportfile" style={{ color: "#87CEFA", textDecoration: "none" }}>
//                         NewPieceImportFile
//                     </Link>
//                 </li>
//             </ul>
//         </div>
//     )
// }
const Home = () => {
    return (
        <>
            <Helmet>
                <title>Home - Explore the datAR Project and Custom Pieces</title>
            </Helmet>
            <Flex gap={{ md: "92px", base: "46px", sm: "69px" }} bg="white.a700" w="100%" flexDirection="column">
                <Flex flexDirection="column" alignItems="center">
                    {/* home section */}
                    <HomeSection />

                    {/* about section */}
                    <AboutSection />
                    <Image
                        src="images/img_ideation_update.png"
                        alt="Ideation Image" h={{
                            md: "614px", base:
                                "auto"
                        }}
                        mt="60px"
                        fit="cover"
                        w="100%"
                        maxw="798px"
                        mx="auto"
                        p={{
                            md: 0, base: "20px"
                        }}
                    />
                    <>
                        {/* home section */}
                        <Flex mt="70px" alignSelf="stretch" justifyContent="center" px={{ md: "56px", base: "20px" }}>
                            <Flex gap="40px" w="100%" maxW="820px" mx="auto" flexDirection={{ md: "row", base: "column" }}>
                                <Suspense fallback={<div>Loading feed...</div>}>
                                    
                                    <HomeButton text="My Custom Pieces" imgsrc="images/bookicon.png" key={"homeList" + 0} />
                                    <HomeButton text="Browse Pieces" imgsrc="images/search.svg" key={"homeList" + 1} />
                                    <HomeButton text="My Classrooms" imgsrc="images/sandbox.svg" key={"homeList" + 2} />
                                </Suspense>
                            </Flex>
                        </Flex>
                    </>
                </Flex>
                <Footer />
            </Flex>
        </>
    );
}
export default Home;